Repository ISISComputingGroup/EPICS-motorExtensions, pull requests merged in 2020-08, with the labels that each got.

#25 Move vacuum tank stop motion to motorExtensions
  sans2dVacTankApp/Db/Makefile
  sans2dVacTankApp/Db/sans2d_vac_tank.substitutions
  sans2dVacTankApp/Db/stop_motion.template
  sans2dVacTankApp/Makefile
  sans2dVacTankApp/src/Makefile
  settings/sans2d/axes.cmd
  settings/sans2d/galil01.cmd
  settings/sans2d/galil02.cmd
  settings/sans2d/galil03.cmd
  settings/sans2d/galil04.cmd
  settings/sans2d/galil05.cmd
  settings/sans2d/jaws.cmd
  settings/sans2d/motionsetpoints.cmd
  settings/sans2d/motorExtensions.cmd
Labels: size/L

#26 Ticket4581 front detector beam stop
  sans2dVacTankApp/Db/inhibit.template
  sans2dVacTankApp/Db/sans2d_vac_tank.substitutions
Labels: size/S

#27 Ticket4571 sans2d apertures guides stop
  sans2dApertureWaveguidesApp/Db/Makefile
  sans2dApertureWaveguidesApp/Db/sans2d_apertures_waveguides.substitutions
  sans2dApertureWaveguidesApp/Db/stop_motion.template
  sans2dApertureWaveguidesApp/Makefile
  sans2dApertureWaveguidesApp/Src/Makefile
  settings/sans2d_apertures_guides/axes.cmd
  settings/sans2d_apertures_guides/galilmul01.cmd
  settings/sans2d_apertures_guides/galilmul02.cmd
  settings/sans2d_apertures_guides/jaws.cmd
  settings/sans2d_apertures_guides/motorExtensions.cmd
  settings/sans2d_vacuum_tank/axes.cmd
  settings/sans2d_vacuum_tank/galil01.cmd
  settings/sans2d_vacuum_tank/galil02.cmd
  settings/sans2d_vacuum_tank/galil03.cmd
  settings/sans2d_vacuum_tank/galil04.cmd
  settings/sans2d_vacuum_tank/galil05.cmd
  settings/sans2d_vacuum_tank/jaws.cmd
  settings/sans2d_vacuum_tank/motionsetpoints.cmd
  settings/sans2d_vacuum_tank/motorExtensions.cmd
Labels: size/M

#28 Added template for positional error
  sans2dApertureWaveguidesApp/Db/positional_error.template
  sans2dApertureWaveguidesApp/Db/sans2d_apertures_waveguides.substitutions
Labels: size/M
