Repository ISISComputingGroup/EPICS-motorExtensions, pull requests merged in 2020-09, with the labels that each got.

#29 Ticket4587 sans2 d baffle detector intervals
  sans2dVacTankApp/Db/sans2d-vac-intervals.template
  sans2dVacTankApp/Db/sans2d_enable_collision_avoidance.template
  sans2dVacTankApp/Db/sans2d_vac_minimum_intervals.template
  sans2dVacTankApp/Db/sans2d_vac_stop_detectors_baffles.template
  sans2dVacTankApp/Db/sans2d_vac_tank.substitutions
  settings/sans2d_vacuum_tank/motorExtensions.cmd
Labels: size/L

#30 Add new line
  sans2dVacTankApp/Db/sans2d_vac_minimum_intervals.template
Labels: size/XS

#31 Fix duplicate pv
  sans2dVacTankApp/Db/sans2d_vac_stop_detectors_baffles.template
Labels: size/S
